# Generated by Django 5.0.7 on 2024-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='crypto_symbol',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='status',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='crypto',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
