# Generated by Django 5.0.7 on 2024-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_alerts', '0002_remove_alert_created_at_remove_alert_crypto_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='crypto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
